                            <aside class="autres-videos">
                                <div class="bloc-figure">
                                    <figure><a href="../un-sourire-espoir3/apaise-ton-coeur.php" title="Apaise ton cœur - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/apaise-ton-coeur.jpg" alt="Apaise ton cœur - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/anniversaire-de-ma-femme.php" title="L'anniversaire de ma femme - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/anniversaire-femme.jpg" alt="L'anniversaire de ma femme - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/les-gros-mots-en-islam.php" title="Les gros mots en islam - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/gros-mots.jpg" alt="Les gros mots en islam - Un sourire d'espoir 3" /></a></figure>
                                    <figure><a href="../un-sourire-espoir3/la-chaussure-de-gandhi.php" title="La chaussure de Gandhi - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/gandhi.jpg" alt="La chaussure de Gandhi - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/un-francais-converti-a-islam.php" title="L'histoire d'un français converti à l'islam - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/francais-converti.jpg" alt="L'histoire d'un français converti à l'islam - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/bonne-fete-des-meres.php" title="Bonne fête des mères - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/fete-meres.jpg" alt="Bonne fête des mères - Un sourire d'espoir 3" /></a></figure>
                                    <figure><a href="../un-sourire-espoir3/epouser-ou-pas.php" title="L'épouser ou pas ? - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/epouser-ou-pas.jpg" alt="L'épouser ou pas ? - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/un-enfant-chez-le-dentiste.php" title="Un enfant chez le dentiste - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/enfant-dentiste.jpg" alt="Un enfant chez le dentiste - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/a-la-recherche-un-travail.php" title="À la recherche d'un travail - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/emploi.jpg" alt="À la recherche d'un travail - Un sourire d'espoir 3" /></a></figure>
                                    <figure><a href="../un-sourire-espoir3/une-famille-elephants.php" title="Une famille d'éléphants - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/famille-elephant.jpg" alt="Une famille d'éléphants - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/une-ecurie-de-chevaux.php" title="Une écurie de chevaux - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/ecurie.jpg" alt="Une écurie de chevaux - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/ecole-de-la-vie.php" title="L'école de la vie - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/ecole-vie.jpg" alt="L'école de la vie - Un sourire d'espoir 3" /></a></figure>
                                    <figure><a href="../un-sourire-espoir3/echouer-dans-la-vie.php" title="Échouer dans la vie - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/echouer.jpg" alt="Échouer dans la vie - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/eau-a-medine.php" title="L'eau à Médine - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/eau-medine.jpg" alt="L'eau à Médine - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/une-histoire-qui-depasse-imagination.php" title="Une histoire qui dépasse l'imagination - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/depasse-imagination.jpg" alt="Une histoire qui dépasse l'imagination - Un sourire d'espoir 3" /></a></figure>
                                    <figure><a href="../un-sourire-espoir3/ne-laisse-pas-les-autres-te-decourager.php" title="Ne laisse pas les autres te décourager - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/decourager.jpg" alt="Ne laisse pas les autres te décourager - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/couvertures-hiver.php" title="Des couvertures d'hiver - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/couverture.jpg" alt="Des couvertures d'hiver - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/la-circulation-en-inde.php" title="La circulation en Inde - Un sourire d'espoir 3"><img src="../img/miniatures-small/saison3/circulation-inde.jpg" alt="La circulation en Inde - Un sourire d'espoir 3" /></a></figure>
                                    <a href="../un-sourire-espoir.php" title="Voir plus d'épisode"><div class="voir-plus"><h3>Voir plus</h3></div></a>
                                </div>
                            </aside>