<!DOCTYPE html>
    <html lang="fr">
        <head>
            <title>Un sourire d'espoir saison 1 - Partie 3 | Amr Khaled en Français</title>
            <meta charset="UTF-8" />
            <meta name="description" content="Première saison de l'émission Un Sourire d'Espoir sur le site AmrKhaledFrancais.com" />
            <link rel="stylesheet" type="text/css" href="../css/styles.css" />
            <!--[if lt IE 9]> <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
        </head>
        <body>
            <div id="conteneur">
                <div class="nav-haut">
                    <div class="logo"><h2>AmrKhaledFrançais.com</h2></div>
                    <nav class="navigation">
                        
                        <ul>
                            <li><a href="../index.php">Accueil</a></li>
                            <li><a href="https://www.youtube.com/channel/UCSslOSQkzVvrMU0aYtYTkUA">Chaine Youtube</a></li>
                            <li><a href="../un-sourire-espoir.php">Un Sourire d'Espoir</a></li>
                            <li><a href="../autres-emissions.php">Autres émissions</a></li>
                            <li><a href="../contact.php">Contact</a></li>
                        </ul>
                        
                    </nav>
                </div>
                <header class="header">
                    <img src="../img/img-header/s1-ep3.jpg" alt="Amr Khaled en Français - Un Sourire d'Espoir Saison3" />
                </header>
                <?php
                    include("../nav-bas.php");
                ?>
                <div class="bloc-page">
                    <!-- Bloc des derniers épisodes ajoutés -->
                    <section class="episodes-page-accueil">
                        <header class="header-section"><h1>Un sourire d'espoir saison 1 - Partie 3</h1></header>
                        <div class="img-episode-saison">
                            <a class="rouge" href="../un-sourire-espoir1/comment-le-prophete-mohamed-a-repondu-aux-insultes.php" title="Comment le Prophète Mohamed (bpsl) a répondu aux insultes"><figure class="saison1-rouge"><p>Comment le Prophète Mohamed (bpsl) a répondu aux insultes</p></figure></a><a class="gris" href="../un-sourire-espoir1/avoir-la-flemme-d-aider.php" title="Avoir la flemme d'aider - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Avoir la flemme d'aider</p></figure></a><a class="rouge" href="../un-sourire-espoir1/le-joueur-de-golf-argentin.php" title="Le joueur de golf argentin - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Le joueur de golf argentin</p></figure></a><figure><a href="../un-sourire-espoir1/si-tu-conduisais-un-train.php" title="Si tu conduisais un train... - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/conduire-train.jpg" alt="Si tu conduisais un train... - Un sourire d'espoir 1" /></a></figure>
                            <a class="gris" href="../un-sourire-espoir1/comment-le-prophete-mohamed-a-repondu-a-la-corruption.php" title="Comment le Prophète Mohamed (bpsl) a répondu à la corruption - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Comment le Prophète Mohamed (bpsl) a répondu à la corruption</p></figure></a><figure><a href="../un-sourire-espoir1/histoire-d-un-papillon.php" title="L'histoire d'un papillon - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/papillon.jpg" alt="L'histoire d'un papillon - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/mon-pere-refuse-de-me-parler.php" title="Mon père refuse de me parler - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Mon père refuse de me parler</p></figure></a><figure><a href="../un-sourire-espoir1/histoire-du-coiffeur-et-l-enfant-idiot.php" title="L'histoire du coiffeur et l'enfant idiot - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/coiffure-enfant-idiot.jpg" alt="L'histoire du coiffeur et l'enfant idiot - Un sourire d'espoir 1" /></a></figure>
                            <a class="rouge" href="../un-sourire-espoir1/comment-le-prophete-mohamed-a-repondu-aux-rumeurs.php" title="Comment le Prophète Mohamed (bpsl) a répondu aux rumeurs - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Comment le Prophète Mohamed (bpsl) a répondu aux rumeurs</p></figure></a><figure><a href="../un-sourire-espoir1/mon-meilleur-ami-m-a-gifle.php" title="Mon meilleur ami m'a giflé - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/ami-gifle.jpg" alt="Mon meilleur ami m'a giflé - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/le-frigo-des-illusions.php" title="Le frigo des illusions - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/frigo-illusions.jpg" alt="Le frigo des illusions - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/conseil-pour-ne-pas-divorcer.php" title="Conseil pour ne pas divorcer - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Conseil pour ne pas divorcer</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/la-vente-aux-encheres-d-un-chateau.php" title="La vente aux enchères d'un château - Un sourire d'espoir 1"><figure class="saison1-gris"><p>La vente aux enchères d'un château</p></figure></a><figure><a href="../un-sourire-espoir1/se-metisser-comme-les-couleurs.php" title="Se métisser comme les couleurs - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/se-metisser-comme-les-couleurs.jpg" alt="Se métisser comme les couleurs - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/histoire-vraie-d-un-homme-devenu-millionnaire.php" title="L'histoire vraie d'un homme devenu millionnaire - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'histoire vraie d'un homme devenu millionnaire</p></figure></a><a class="rouge" href="../un-sourire-espoir1/la-plus-belle-histoire-du-monde-en-trois-minutes.php" title="La plus belle histoire du monde en 3 minutes - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>La plus belle histoire du monde en 3 minutes</p></figure></a>
                            <a class="rouge" href="../un-sourire-espoir1/je-l-aime-mais-il-ne-veut-pas-m-epouser.php" title="Je l'aime, mais il ne veut pas m'épouser... - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Je l'aime, mais il ne veut pas m'épouser...</p></figure></a><a class="gris" href="../un-sourire-espoir1/sois-comme-la-vierge-marie.php" title="Sois comme la vierge Marie - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Sois comme la vierge Marie</p></figure></a><a class="rouge" href="../un-sourire-espoir1/comment-conseiller-sans-brusquer.php" title="Comment conseiller sans brusquer - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Comment conseiller sans brusquer</p></figure></a><a class="gris" href="../un-sourire-espoir1/pour-que-l-amour-dure-des-annees-apres-ton-mariage.php" title="Pour que l'amour dure des années après ton mariage - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Pour que l'amour dure des années après ton mariage</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/les-photos-de-nos-enfants.php" title="Les photos de nos enfants - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Les photos de nos enfants</p></figure></a><a class="rouge" href="../un-sourire-espoir1/un-conseil-important-a-tous-les-fiances.php" title="Un conseil important à tous les fiancés - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Un conseil important à tous les fiancés</p></figure></a><a class="gris" href="../un-sourire-espoir1/histoire-vraie-d-un-opticien.php" title="L'histoire vraie d'un opticien - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'histoire vraie d'un opticien</p></figure></a><a class="rouge" href="../un-sourire-espoir1/se-faire-respecter-par-tout-le-monde.php" title="Se faire respecter par tout le monde - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Se faire respecter par tout le monde</p></figure></a>
                            <a class="rouge" href="../un-sourire-espoir1/un-nombre-determine-de-jours.php" title="{Un nombre déterminé de jours} Sourate Al-Baqara : La Vache - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>{Un nombre déterminé de jours} Sourate Al-Baqara : La Vache</p></figure></a><a class="gris" href="../un-sourire-espoir1/ta-vie-est-comme-un-tir-a-l-arc.php" title="Ta vie est comme un tir à l'arc - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Ta vie est comme un tir à l'arc</p></figure></a><a class="rouge" href="../un-sourire-espoir1/comment-on-m-a-vole-mon-telephone-portable.php" title="Comment on m'a volé mon téléphone portable - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Comment on m'a volé mon téléphone portable</p></figure></a><a class="gris" href="../un-sourire-espoir1/comment-savoir-si-on-est-vraiment-amoureux.php" title="Comment savoir si on est vraiment amoureux - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Comment savoir si on est vraiment amoureux</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/40-jours-dans-la-mosquee-du-prophete.php" title="40 jours dans la mosquée du Prophète (bpsl) - Un sourire d'espoir 1"><figure class="saison1-gris"><p>40 jours dans la mosquée du Prophète (bpsl)</p></figure></a><a class="rouge" href="../un-sourire-espoir1/un-vol-pour-munich.php" title="Un vol pour Munich - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Un vol pour Munich</p></figure></a><a class="gris" href="../un-sourire-espoir1/comment-accueillir-le-ramadan.php" title="Comment accueillir le Ramadan - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Comment accueillir le Ramadan</p></figure></a><a class="rouge" href="../un-sourire-espoir1/etre-serein-le-jour-de-la-resurrection.php" title="Être serein le jour de la résurrection - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Être serein le jour de la résurrection</p></figure></a>
                            <a class="rouge" href="../un-sourire-espoir1/le-tres-reconnaissant.php" title="Un des secrets des 99 noms de Dieu {Le Très-Reconnaissant} - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Un des secrets des 99 noms de Dieu {Le Très-Reconnaissant}</p></figure></a><figure><a href="../un-sourire-espoir1/le-sachet-de-pop-corn.php" title="Le sachet de pop-corn - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/sachet-pop-corn.jpg" alt="Le sachet de pop-corn - Un sourire d'espoir 1" /></a></figure><a class="rouge" href="../un-sourire-espoir1/accord-des-philosophes.php" title="L'accord des philosophes - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>L'accord des philosophes</p></figure></a><a class="gris" href="../un-sourire-espoir1/mon-frere-m-a-arnaque.php" title="Mon frère m'a arnaqué - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Mon frère m'a arnaqué</p></figure></a>
                            <figure><a href="../un-sourire-espoir1/comment-devenir-moins-nerveux.php" title="Comment devenir moins nerveux - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/devenir-moins-nerveux.jpg" alt="Comment devenir moins nerveux - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/petit-exercice-de-mathematiques.php" title="Petit exercice de mathématiques (pas comme les autres) - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/exercice-maths.jpg" alt="Petit exercice de mathématiques (pas comme les autres) - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/aider-une-personne-handicapee.php" title="Aider une personne handicapée - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Aider une personne handicapée</p></figure></a><a class="rouge" href="../un-sourire-espoir1/la-modestie-envers-les-parents.php" title="La modestie envers les parents - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>La modestie envers les parents</p></figure></a>
                            <figure><a href="../un-sourire-espoir1/general-motors-et-la-glace-a-la-vanille.php" title="General Motors et la glace à la vanille - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/general-motors-glace-vanille.jpg" alt="General Motors et la glace à la vanille - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/la-difficulte-d-exprimer-nos-sentiments.php" title="La difficulté d'exprimer nos sentiments - Un sourire d'espoir 1"><figure class="saison1-gris"><p>La difficulté d'exprimer nos sentiments</p></figure></a><a class="rouge" href="../un-sourire-espoir1/un-poeme-pour-toutes-les-mamans.php" title="Un poème pour toutes les mamans - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Un poème pour toutes les mamans</p></figure></a><figure><a href="../un-sourire-espoir1/la-roue-tourne.php" title="La roue tourne (une histoire vraie) - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/la-roue-tourne.jpg" alt="La roue tourne (une histoire vraie) - Un sourire d'espoir 1" /></a></figure>
                            <figure><a href="../un-sourire-espoir1/rever-en-couleur-comme-andre-agassi.php" title="Rêver en couleur comme Andre Agassi - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/rever-en-couleur.jpg" alt="Rêver en couleur comme Andre Agassi - Un sourire d'espoir 1" /></a></figure><a class="rouge" href="../un-sourire-espoir1/la-mauvaise-epouse.php" title="La mauvaise épouse - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>La mauvaise épouse</p></figure></a><a class="gris" href="../un-sourire-espoir1/combien-de-pompes-es-tu-capable-de-faire.php" title="Combien de pompes es-tu capable de faire? - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Combien de pompes es-tu capable de faire?</p></figure></a><a class="rouge" href="../un-sourire-espoir1/une-histoire-drole-pour-tous-les-impatients.php" title="Une histoire drôle pour tous les impatients - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Une histoire drôle pour tous les impatients</p></figure></a>
                            <a class="rouge" href="../un-sourire-espoir1/les-meilleurs-commercants.php" title="Les meilleurs commerçants - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Les meilleurs commerçants</p></figure></a><figure><a href="../un-sourire-espoir1/histoire-de-deux-chevaux.php" title="L'histoire de deux chevaux - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/histoire-deux-chevaux.jpg" alt="L'histoire de deux chevaux - Un sourire d'espoir 1" /></a></figure><a class="rouge" href="../un-sourire-espoir1/les-deux-associes-musulman-et-chretien.php" title="Les deux associés musulman et chrétien - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Les deux associés musulman et chrétien</p></figure></a><a class="gris" href="../un-sourire-espoir1/un-cafe-gratuit.php" title="Un café gratuit - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Un café gratuit</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/le-tableau-le-plus-cher-du-monde.php" title="Le tableau le plus cher du monde - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Le tableau le plus cher du monde</p></figure></a>
                        </div>
                        <footer class="footer-episode-saison">
                            <div class="pagination"><a href="saison1-part1.php" title="Un Sourire d'espoir saison 1 - Page 1">1</a><a href="saison1-part2.php" title="Un Sourire d'espoir saison 2 - Page 1">2</a><p class="lien-active" title="Un Sourire d'espoir saison 1 - Page 3">3</p></div>
                        </footer>
                    </section>
                            <?php
                            include("../pub.php");
                            ?>
                </div>
                </div>
        </body>
    </html>