<!DOCTYPE html>
    <html lang="fr">
        <head>
            <title>Un sourire d'espoir saison 1 - Partie 2 | Amr Khaled en Français</title>
            <meta charset="UTF-8" />
            <meta name="description" content="Première saison de l'émission Un Sourire d'Espoir sur le site AmrKhaledFrancais.com" />
            <link rel="stylesheet" type="text/css" href="../css/styles.css" />
            <!--[if lt IE 9]> <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
        </head>
        <body>
            <div id="conteneur">
                <div class="nav-haut">
                    <div class="logo"><h2>AmrKhaledFrançais.com</h2></div>
                    <nav class="navigation">
                        
                        <ul>
                            <li><a href="../index.php">Accueil</a></li>
                            <li><a href="https://www.youtube.com/channel/UCSslOSQkzVvrMU0aYtYTkUA">Chaine Youtube</a></li>
                            <li><a href="../un-sourire-espoir.php">Un Sourire d'Espoir</a></li>
                            <li><a href="../autres-emissions.php">Autres émissions</a></li>
                            <li><a href="../contact.php">Contact</a></li>
                        </ul>
                        
                    </nav>
                </div>
                <header class="header">
                    <img src="../img/img-header/s1-ep2.jpg" alt="Amr Khaled en Français - Un Sourire d'Espoir Saison3" />
                </header>
                <?php
                    include("../nav-bas.php");
                ?>
                <div class="bloc-page">
                    <!-- Bloc des derniers épisodes ajoutés -->
                    <section class="episodes-page-accueil">
                        <header class="header-section"><h1>Un sourire d'espoir saison 1 - Partie 2</h1></header>
                        <div class="img-episode-saison">
                            <figure><a href="../un-sourire-espoir1/les-gens-et-leurs-masques.php" title="Les gens et leurs masques - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/les-gens-et-leurs-masques.jpg" alt="Les gens et leurs masques - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/l-adolescent-qui-se-noyait.php" title="L'adolescent qui se noyait - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/adolescent-qui-se-noyait.jpg" alt="L'adolescent qui se noyait - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/la-maladie-de-l-oubli.php" title="La maladie de l'oubli - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/maladie-oubli.jpg" alt="La maladie de l'oubli - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/methode-pour-resoudre-tous-nos-problemes.php" title="Méthode pour résoudre tous nos problèmes - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Méthode pour résoudre tous nos problèmes</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/ecrivain-marocain-audacieux.php" title="L'écrivain marocain audacieux - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'écrivain marocain audacieux</p></figure></a><a class="rouge" href="../un-sourire-espoir1/une-histoire-d-amour-triste.php" title="Une histoire d'amour triste - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Une histoire d'amour triste</p></figure></a><a class="gris" href="../un-sourire-espoir1/d-une-pierre-trois-coups.php" title="D'une pierre 3 coups - Un sourire d'espoir 1"><figure class="saison1-gris"><p>D'une pierre 3 coups</p></figure></a><figure><a href="../un-sourire-espoir1/sauver-un-poussin.php" title="Sauver un poussin - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/sauver-poussin.jpg" alt="Sauver un poussin - Un sourire d'espoir 1" /></a></figure>
                            <a class="rouge" href="../un-sourire-espoir1/un-sourire-d-espoir-des-iles-comores.php" title="Un sourire d'espoir des iles Comores - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Un sourire d'espoir des iles Comores</p></figure></a><a class="gris" href="../un-sourire-espoir1/le-sultan-deteste-par-son-peuple.php" title="Le sultan détesté par son peuple - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Le sultan détesté par son peuple</p></figure></a><a class="rouge" href="../un-sourire-espoir1/le-portrait-du-roi-defigure.php" title="Le portrait du roi défiguré - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Le portrait du roi défiguré</p></figure></a><a class="gris" href="../un-sourire-espoir1/enfant-et-le-coffre-rempli-de-bijoux.php" title="L'enfant et le coffre rempli de bijoux - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'enfant et le coffre rempli de bijoux</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/deviens-riche-grace-a-ta-famille.php" title="Deviens riche grâce à ta famille - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Deviens riche grâce à ta famille</p></figure></a><figure><a href="../un-sourire-espoir1/des-expressions-qui-font-rire.php" title="Des expressions qui font rire - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/expressions-qui-font-rire.jpg" alt="Des expressions qui font rire - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/comment-se-debarrasser-de-nos-mauvaises-habitudes.php" title="Comment se débarrasser de nos mauvaises habitudes - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Comment se débarrasser de nos mauvaises habitudes</p></figure></a><a class="rouge" href="../un-sourire-espoir1/la-technique-des-herissons.php" title="La technique des hérissons (un conseil pour les filles) - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>La technique des hérissons (un conseil pour les filles)</p></figure></a>
                            <figure><a href="../un-sourire-espoir1/le-concours-du-meilleur-mais-en-irak.php" title="Le concours du meilleur maïs en Irak - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/concours-mais-irak.jpg" alt="Le concours du meilleur maïs en Irak - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/les-etoiles-de-mer-au-mexique.php" title="Les étoiles de mer au Mexique - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/etoiles-mer-mexique.jpg" alt="Les étoiles de mer au Mexique - Un sourire d'espoir 1" /></a></figure><a class="rouge" href="../un-sourire-espoir1/la-robe-de-mariee.php" title="La robe de mariée - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>La robe de mariée</p></figure></a><a class="gris" href="../un-sourire-espoir1/appel-a-la-priere-d-un-adolescent.php" title="L'appel à la prière d'un adolescent - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'appel à la prière d'un adolescent</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/humour-du-prophete-mohamed.php" title="L'humour du Prophète Mohamed (bpsl) - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'humour du Prophète Mohamed (bpsl)</p></figure></a><figure><a href="../un-sourire-espoir1/les-quatre-princes-et-l-arbre-de-peches.php" title="Les 4 princes et l'arbre de pêches - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/princes-arbre-peches.jpg" alt="Les 4 princes et l'arbre de pêches - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/faire-partie-des-premiers.php" title="Faire partie des premiers - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Faire partie des premiers</p></figure></a><a class="rouge" href="../un-sourire-espoir1/obtenir-une-promotion-au-travail.php" title="Obtenir une promotion au travail - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Obtenir une promotion au travail</p></figure></a>
                            <a class="rouge" href="../un-sourire-espoir1/epouse-qui-n-a-pas-de-prix.php" title="L'épouse qui n'a pas de prix - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>L'épouse qui n'a pas de prix</p></figure></a><a class="gris" href="../un-sourire-espoir1/oncle-mutwali.php" title="L'oncle Mutwali - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'oncle Mutwali</p></figure></a><a class="rouge" href="../un-sourire-espoir1/le-createur-de-fedex.php" title="Le créateur de FedEx - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Le créateur de FedEx</p></figure></a><a class="gris" href="../un-sourire-espoir1/epouse-sourde.php" title="L'épouse sourde - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'épouse sourde</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/influence-des-amis.php" title="L'influence des amis - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'influence des amis</p></figure></a><a class="rouge" href="../un-sourire-espoir1/invocation-des-bebes-corbeaux.php" title="L'invocation des bébés corbeaux - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>L'invocation des bébés corbeaux</p></figure></a><a class="gris" href="../un-sourire-espoir1/le-voleur-de-linge-et-de-portefeuilles.php" title="Le voleur de linge et de portefeuilles - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Le voleur de linge et de portefeuilles</p></figure></a><a class="rouge" href="../un-sourire-espoir1/comment-affronter-dix-personnes.php" title="Comment affronter 10 personnes - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Comment affronter 10 personnes</p></figure></a>
                            <a class="rouge" href="../un-sourire-espoir1/participer-avant-de-conseiller-comme-le-prophete.php" title="Participer avant de conseiller comme le Prophète (bpsl) - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Participer avant de conseiller comme le Prophète (bpsl)</p></figure></a><a class="gris" href="../un-sourire-espoir1/comment-reconcilier-des-parents-divorces.php" title="Comment réconcilier des parents divorcés - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Comment réconcilier des parents divorcés</p></figure></a><figure><a href="../un-sourire-espoir1/le-prophete-le-verre-d-eau-et-l-enfant.php" title="Le Prophète (bpsl), le verre d'eau et l'enfant - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/prophete-verre-eau.jpg" alt="Le Prophète (bpsl), le verre d'eau et l'enfant - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/la-lecture-du-coran-le-sac-et-la-plage.php" title="La lecture du Coran, le sac et la plage - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/coran-sac-plage.jpg" alt="La lecture du Coran, le sac et la plage - Un sourire d'espoir 1" /></a></figure>
                            <figure><a href="../un-sourire-espoir1/la-mere-qui-se-laissait-aller.php" title="La mère qui se laissait aller - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/mere-laiser-aller.jpg" alt="La mère qui se laissait aller - Un sourire d'espoir 1" /></a></figure><a class="rouge" href="../un-sourire-espoir1/soignez-vos-malades-avec-aumone.php" title="Soignez vos malades avec l'aumône - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Soignez vos malades avec l'aumône</p></figure></a><a class="gris" href="../un-sourire-espoir1/es-tu-fidele-comme-le-prophete-mohamed.php" title="Es-tu fidèle comme le Prophète Mohamed (pbsl) ? - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Es-tu fidèle comme le Prophète Mohamed (pbsl) ?</p></figure></a><a class="rouge" href="../un-sourire-espoir1/la-mendicite-des-enfants-de-la-rue.php" title="La mendicité des enfants de la rue - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>La mendicité des enfants de la rue</p></figure></a>
                            <a class="rouge" href="../un-sourire-espoir1/les-trois-lecons-du-lord-anglais.php" title="Les 3 leçons du lord anglais - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Les 3 leçons du lord anglais</p></figure></a><a class="gris" href="../un-sourire-espoir1/comment-trouver-un-mari.php" title="Comment trouver un mari - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Comment trouver un mari</p></figure></a><a class="rouge" href="../un-sourire-espoir1/la-chaleur-des-tunisiens.php" title="La chaleur des tunisiens - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>La chaleur des tunisiens</p></figure></a><figure><a href="../un-sourire-espoir1/apprendre-a-faire-du-velo-a-un-enfant.php" title="Apprendre à faire du vélo à un enfant - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/velo-enfant.jpg" alt="Apprendre à faire du vélo à un enfant - Un sourire d'espoir 1" /></a></figure>
                            <a class="gris" href="../un-sourire-espoir1/une-femme-syrienne-exemplaire.php" title="Une femme syrienne exemplaire - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Une femme syrienne exemplaire</p></figure></a><a class="rouge" href="../un-sourire-espoir1/comment-aller-au-paradis.php" title="Comment aller au Paradis - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Comment aller au Paradis</p></figure></a><a class="gris" href="../un-sourire-espoir1/la-phase-terminale-d-un-cancer.php" title="La phase terminale d'un cancer - Un sourire d'espoir 1"><figure class="saison1-gris"><p>La phase terminale d'un cancer</p></figure></a><a class="rouge" href="../un-sourire-espoir1/le-coran-amitie-et-les-parents.php" title="Le Coran, l'amitié et les parents... - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Le Coran, l'amitié et les parents...</p></figure></a>
                            <a class="rouge" href="../un-sourire-espoir1/la-fete-des-meres.php" title="La fête des mères - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>La fête des mères</p></figure></a><a class="gris" href="../un-sourire-espoir1/qui-gagne-plus-le-gentil-ou-le-malin.php" title="Qui gagne plus, le gentil ou le malin? - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Qui gagne plus, le gentil ou le malin?</p></figure></a><a class="rouge" href="../un-sourire-espoir1/par-misericorde-abaisse-pour-eux-aile-de-humilite.php" title="{Et par miséricorde, abaisse pour eux l'aile de l'humilité...} - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>{Et par miséricorde, abaisse pour eux l'aile de l'humilité...}</p></figure></a><a class="gris" href="../un-sourire-espoir1/es-tu-juste-avec-tes-enfants.php" title="Es-tu juste avec tes enfants? - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Es-tu juste avec tes enfants?</p></figure></a>
                        </div>
                        <footer class="footer-episode-saison">
                            <div class="pagination"><a href="saison1-part1.php" title="Un Sourire d'espoir saison 1 - Page 1">1</a><p class="lien-active" title="Un Sourire d'espoir saison 1 - Page 2">2</p><a href="saison1-part3.php" title="Un Sourire d'espoir saison 1 - Page 3">3</a></div>
                        </footer>
                    </section>
                            <?php
                            include("../pub.php");
                            ?>
                </div>
                </div>
        </body>
    </html>