<!DOCTYPE html>
    <html lang="fr">
        <head>
            <title>Un sourire d'espoir saison 1 - Partie 1 | Amr Khaled en Français</title>
            <meta charset="UTF-8" />
            <meta name="description" content="Première saison de l'émission Un Sourire d'Espoir sur le site AmrKhaledFrancais.com" />
            <link rel="stylesheet" type="text/css" href="../css/styles.css" />
            <!--[if lt IE 9]> <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
        </head>
        <body>
            <div id="conteneur">
                <div class="nav-haut">
                    <div class="logo"><h2>AmrKhaledFrançais.com</h2></div>
                    <nav class="navigation">
                        
                        <ul>
                            <li><a href="../index.php">Accueil</a></li>
                            <li><a href="https://www.youtube.com/channel/UCSslOSQkzVvrMU0aYtYTkUA">Chaine Youtube</a></li>
                            <li><a href="../un-sourire-espoir.php">Un Sourire d'Espoir</a></li>
                            <li><a href="../autres-emissions.php">Autres émissions</a></li>
                            <li><a href="../contact.php">Contact</a></li>
                        </ul>
                        
                    </nav>
                </div>
                <header class="header">
                    <img src="../img/img-header/s1-ep1.jpg" alt="Amr Khaled en Français - Un Sourire d'Espoir Saison3" />
                </header>
                <?php
                    include("../nav-bas.php");
                ?>
                <div class="bloc-page">
                    <!-- Bloc des derniers épisodes ajoutés -->
                    <section class="episodes-page-accueil">
                        <header class="header-section"><h1>Un sourire d'espoir saison 1 - Partie 1</h1></header>
                        <div class="img-episode-saison">
                            <a class="gris" href="../un-sourire-espoir1/amour-veritable.php" title="L'amour véritable - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'amour véritable</p></figure></a><a class="rouge" href="../un-sourire-espoir1/le-prophete-mohamed-et-l-amour.php" title="Le Prophète Mohamed (pbsl) et l'amour - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Le Prophète Mohamed (pbsl) et l'amour</p></figure></a><a class="gris" href="../un-sourire-espoir1/comment-voyager-leger.php" title="Comment voyager léger - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Comment voyager léger</p></figure></a><a class="rouge" href="../un-sourire-espoir1/du-nettoyage-de-carrelage-au-sommet-de-la-reussite.php" title="Du nettoyage de carrelage au sommet de la réussite - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Du nettoyage de carrelage au sommet de la réussite</p></figure></a>
                            <a class="rouge" href="../un-sourire-espoir1/o-allah-etend-ma-voix-a-tous-les-horizons.php" title="Ô Allah étend ma voix à tous les horizons - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Ô Allah étend ma voix à tous les horizons</p></figure></a><a class="gris" href="../un-sourire-espoir1/le-vieux-mecanicien-et-le-moteur-du-bateau.php" title="Le vieux mécanicien et le moteur du bateau - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Le vieux mécanicien et le moteur du bateau</p></figure></a><a class="rouge" href="../un-sourire-espoir1/la-fidelite-dans-le-couple.php" title="La fidélité dans le couple - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>La fidélité dans le couple</p></figure></a><a class="gris" href="../un-sourire-espoir1/la-course-de-kayak-entre-arabes-et-japonais.php" title="La course de kayak entre arabes et japonais - Un sourire d'espoir 1"><figure class="saison1-gris"><p>La course de kayak entre arabes et japonais</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/une-nouvelle-facon-d-eduquer-nos-enfants.php" title="Une nouvelle façon d'éduquer nos enfants - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Une nouvelle façon d'éduquer nos enfants</p></figure></a><a class="rouge" href="../un-sourire-espoir1/a-tous-les-parents-qui-souffrent-pour-leurs-enfants.php" title="À tous les parents qui souffrent pour leurs enfants - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>À tous les parents qui souffrent pour leurs enfants</p></figure></a><a class="gris" href="../un-sourire-espoir1/histoire-d-un-commandant-sans-soldats.php" title="L'histoire d'un commandant sans soldats - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'histoire d'un commandant sans soldats</p></figure></a><a class="rouge" href="../un-sourire-espoir1/papa-la-fete-est-arrivee.php" title="Papa la fête est arrivée! - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Papa la fête est arrivée!</p></figure></a>    
                            <figure><a href="../un-sourire-espoir1/histoire-de-la-beaute-la-laideur-et-les-faux-habits.php" title="L'histoire de la beauté, la laideur et les faux habits - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/laideur-faux-habits.jpg" alt="L'histoire de la beauté, la laideur et les faux habits - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/presse-ton-temps-comme-une-orange.php" title="Presse ton temps comme une orange - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/presse-ton-temps.jpg" alt="Presse ton temps comme une orange - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/sois-juste-comme-zlatan-ibrahimovic.php" title="Sois juste comme Zlatan Ibrahimovic - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/zlatan.jpg" alt="Sois juste comme Zlatan Ibrahimovic - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/comment-gagner-les-coeurs-des-gens-en-20-secondes.php" title="Comment gagner les coeurs des gens en 20 secondes - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Comment gagner les coeurs des gens en 20 secondes</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/apprenons-de-l-art-de-conduire-une-voiture.php" title="Apprenons de l'art de conduire une voiture - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Apprenons de l'art de conduire une voiture</p></figure></a><a class="rouge" href="../un-sourire-espoir1/les-endurants-auront-leur-pleine-recompense-sans-compter.php" title="{Les endurants auront leur pleine récompense sans compter} - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>{Les endurants auront leur pleine récompense sans compter}</p></figure></a><a class="gris" href="../un-sourire-espoir1/change-de-cle-avec-tes-enfants.php" title="Change de clé avec tes enfants - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Change de clé avec tes enfants</p></figure></a><a class="rouge" href="../un-sourire-espoir1/ne-privez-pas-vos-filles-d-amour.php" title="Ne privez pas vos filles d'amour - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Ne privez pas vos filles d'amour</p></figure></a>
                            <figure><a href="../un-sourire-espoir1/histoire-de-enfant-et-la-glace-au-chocolat.php" title="L'histoire de l'enfant et la glace au chocolat - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/glace.jpg" alt="L'histoire de l'enfant et la glace au chocolat - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/histoire-vraie-d-un-chirurgien-dentiste.php" title="L'histoire vraie d'un chirurgien dentiste - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/dentiste1.jpg" alt="L'histoire vraie d'un chirurgien dentiste - Un sourire d'espoir 1" /></a></figure><a class="rouge" href="../un-sourire-espoir1/art-de-detecter-les-talents.php" title="L'art de détecter les talents - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>L'art de détecter les talents</p></figure></a><a class="gris" href="../un-sourire-espoir1/garde-toujours-un-espoir-comme-la-turquie.php" title="Garde toujours un espoir comme la Turquie - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Garde toujours un espoir comme la Turquie</p></figure></a>
                            <a class="rouge" href="../un-sourire-espoir1/art-de-corriger-le-fautif.php" title="L'art de corriger le fautif - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>L'art de corriger le fautif</p></figure></a><a class="gris" href="../un-sourire-espoir1/un-des-secrets-des-99-noms-de-dieu-ample.php" title="Un des secrets des 99 noms de Dieu : {L'Ample} - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Un des secrets des 99 noms de Dieu : {L'Ample}</p></figure></a><figure><a href="../un-sourire-espoir1/histoire-de-la-porte-ouverte.php" title="L'histoire de la porte ouverte - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/porte.jpg" alt="L'histoire de la porte ouverte - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/histoire-vraie-du-petit-adam.php" title="L'histoire vraie du petit Adam - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/histoire-petit-adam.jpg" alt="L'histoire vraie du petit Adam - Un sourire d'espoir 1" /></a></figure>
                            <a class="gris" href="../un-sourire-espoir1/sois-loyal-tu-deviendras-elu.php" title="Sois loyal tu deviendras élu - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Sois loyal tu deviendras élu</p></figure></a><figure><a href="../un-sourire-espoir1/histoire-du-chateau-aux-500-chambres.php" title="L'histoire du château aux 500 chambres - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/chateau5.jpg" alt="L'histoire du château aux 500 chambres - Un sourire d'espoir 1" /></a></figure><a class="rouge" href="../un-sourire-espoir1/je-t-aime-sans-conditions.php" title="Je t'aime sans conditions - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>Je t'aime sans conditions</p></figure></a><figure><a href="../un-sourire-espoir1/accepte-les-changements-de-la-vie-avec-flexibilite.php" title="Accepte les changements de la vie avec flexibilité - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/accepte-changement.jpg" alt="Accepte les changements de la vie avec flexibilité - Un sourire d'espoir 1" /></a></figure>
                            <a class="rouge" href="../un-sourire-espoir1/histoire-de-leila-la-musulmane-et-sa-grand-mere-chretienne.php" title="L'histoire de Leila la jeune musulmane et sa grand mère chrétienne - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>L'histoire de Leila la jeune musulmane et sa grand mère chrétienne</p></figure></a><figure><a href="../un-sourire-espoir1/decouvre-le-tresor-qui-est-en-toi.php" title="Découvre le trésor qui est en toi - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/decouvre-tresor.jpg" alt="Découvre le trésor qui est en toi - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/anthony-flew-et-la-correction-du-trajet.php" title="Anthony Flew et la correction du trajet - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/flew.jpg" alt="Anthony Flew et la correction du trajet - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/je-suis-desole.php" title="Je suis désolé - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Je suis désolé</p></figure></a>
                            <a class="gris" href="../un-sourire-espoir1/histoire-du-voisin-anglais.php" title="L'histoire du voisin anglais d'Amr Khaled - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'histoire du voisin anglais d'Amr Khaled</p></figure></a><figure><a href="../un-sourire-espoir1/integrite-au-japon.php" title="L'intégrité au Japon - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/integrite.jpg" alt="L'intégrité au Japon - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/bouge-et-renouvelle-ta-vie.php" title="Bouge et renouvelle ta vie - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/bouge-et-renouvelle.jpg" alt="Bouge et renouvelle ta vie - Un sourire d'espoir 1" /></a></figure><a class="rouge" href="../un-sourire-espoir1/ma-misericorde-embrasse-toute-chose.php" title="{Et Ma miséricorde embrasse toute chose} - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>{Et Ma miséricorde embrasse toute chose}</p></figure></a>
                            <figure><a href="../un-sourire-espoir1/la-soif-apprendre.php" title="La soif d'apprendre - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/soif-apprendre.jpg" alt="La soif d'apprendre - Un sourire d'espoir 1" /></a></figure><a class="gris" href="../un-sourire-espoir1/quelles-sont-les-bonnes-oeuvres-qui-persistent.php" title="Quelles sont les bonnes œuvres qui persistent? - Un sourire d'espoir 1"><figure class="saison1-gris"><p>Quelles sont les bonnes œuvres qui persistent?</p></figure></a><a class="rouge" href="../un-sourire-espoir1/amour-entre-homme-et-la-femme.php" title="L'amour entre l'homme et la femme - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>L'amour entre l'homme et la femme</p></figure></a><a class="gris" href="../un-sourire-espoir1/histoire-un-jeune-homme-au-coeur-tendre.php" title="L'histoire d'un jeune homme au coeur tendre - Un sourire d'espoir 1"><figure class="saison1-gris"><p>L'histoire d'un jeune homme au coeur tendre</p></figure></a>
                            <figure><a href="../un-sourire-espoir1/le-pere-ami.php" title="Le père ami - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/pere-ami-s1.jpg" alt="Le père ami - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/histoire-de-elephant-prisonnier.php" title="L'histoire de l'éléphant prisonnier - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/elephant.jpg" alt="L'histoire de l'éléphant prisonnier - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/le-plaisir-de-recevoir-et-donner.php" title="Le plaisir de recevoir et donner - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/recevoir-et-donner.jpg" alt="Le plaisir de recevoir et donner - Un sourire d'espoir 1" /></a></figure><a class="rouge" href="../un-sourire-espoir1/histoire-du-vendeur-de-poissons.php" title="L'histoire du vendeur de poissons - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>L'histoire du vendeur de poissons</p></figure></a>
                            <figure><a href="../un-sourire-espoir1/le-secret-du-football.php" title="Le secret du football - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/football-img.jpg" alt="Le secret du football - Un sourire d'espoir 1" /></a></figure><figure><a href="../un-sourire-espoir1/la-sagesse-d-un-cheval.php" title="La sagesse d'un cheval - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/sagesse-cheval.jpg" alt="La sagesse d'un cheval - Un sourire d'espoir 1" /></a></figure><a class="rouge" href="../un-sourire-espoir1/c-est-peut-etre-un-bien.php" title="C'est peut-être un bien - Un sourire d'espoir 1"><figure class="saison1-rouge"><p>C'est peut-être un bien</p></figure></a><figure><a href="../un-sourire-espoir1/sois-grand-telle-une-girafe.php" title="Sois grand telle une girafe - Un sourire d'espoir 1"><img src="../img/img-saison/saison1/girafe-sois-grand.jpg" alt="Sois grand telle une girafe - Un sourire d'espoir 1" /></a></figure>
                        </div>
                        <footer class="footer-episode-saison">
                            <div class="pagination"><p class="lien-active" title="Un Sourire d'espoir saison 3 - Page 1">1</p><a href="saison1-part2.php" title="Un Sourire d'espoir saison 2 - Page 2">2</a><a href="saison1-part3.php" title="Un Sourire d'espoir saison 2 - Page 3">3</a></div>
                        </footer>
                    </section>
                            <?php
                            include("../pub.php");
                            ?>
                </div>
                </div>
        </body>
    </html>