<!DOCTYPE html>
    <html lang="fr">
        <head>
            <title>Un sourire d'espoir saison 3 | Amr Khaled en Français</title>
            <meta charset="UTF-8" />
            <link rel="stylesheet" type="text/css" href="../css/styles.css" />
            <!--[if lt IE 9]> <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
        </head>
        <body>
            <div id="conteneur">
                <div class="nav-haut">
                    <div class="logo"><h2>AmrKhaledFrançais.com</h2></div>
                    <nav class="navigation">
                        
                        <ul>
                            <li><a href="../index.php">Accueil</a></li>
                            <li><a href="https://www.youtube.com/channel/UCSslOSQkzVvrMU0aYtYTkUA">Chaine Youtube</a></li>
                            <li><a href="../un-sourire-espoir.php">Un Sourire d'Espoir</a></li>
                            <li><a href="../autres-emissions.php">Autres émissions</a></li>
                            <li><a href="../contact.php">Contact</a></li>
                        </ul>
                        
                    </nav>
                </div>
                <header class="header">
                    <img src="../img/test2.jpg" alt="Amr Khaled en Français - Un Sourire d'Espoir Saison3" />
                </header>
                <?php
                    include("../nav-bas.php");
                ?>
                <div class="bloc-page">
                    <!-- Bloc des derniers épisodes ajoutés -->
                    <section class="episodes-page-accueil">
                        <header class="header-section"><h1>Un sourire d'espoir saison 3</h1></header>
                        <div class="img-episode-saison">
                                <figure><a href="../un-sourire-espoir3/le-retour-des-vacances.php" title="Le retour des vacances - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/retour-vacances.jpg" alt="Le retour des vacances - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/les-dix-jours-de-dhul-hijja.php" title="Les 10 jours de Dhûl Hijja - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/dhul-hijja.jpg" alt="Les 10 jours de Dhûl Hijja - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/le-tableau-espagnol.php" title="Le tableau espagnol - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/tableau-espagnol.jpg" alt="Le tableau espagnol - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/le-jour-d-arafat.php" title="Le jour d'Arafat - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/arafat.jpg" alt="Le jour d'Arafat - Un sourire d'espoir 3" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/histoire-d-un-jeune-ecrivain.php" title="L'histoire d'un jeune écrivain - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/jeune-ecrivain.jpg" alt="L'histoire d'un jeune écrivain - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/les-gros-mots-en-islam.php" title="Les gros mots en islam - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/gros-mots.jpg" alt="Les gros mots en islam - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/rater-un-entretien-d-embauche.php" title="Rater un entretien d'embauche - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/rater-entretien-embauche.jpg" alt="Rater un entretien d'embauche - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/un-restaurant-halal.php" title="Un restaurant Halal - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/restaurant-halal.jpg" alt="Un restaurant Halal - Un sourire d'espoir 3" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/le-palais-du-moi.php" title="Le palais du Moi - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/palais-du-moi.jpg" alt="Le palais du Moi - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/le-cercle-du-bien.php" title="Le cercle du bien - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/cercle-du-bien.jpg" alt="Le cercle du bien - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/les-robes-de-la-reine-indienne.php" title="Les robes de la reine indienne - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/reine-indienne.jpg" alt="Les robes de la reine indienne - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/inventeur-d-hotmail.php" title="L'inventeur d'Hotmail - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/inventeur-hotmail.jpg" alt="L'inventeur d'hotmail - Un sourire d'espoir 3" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/un-miracle-avec-un-dollar.php" title="Un miracle avec 1 dollar - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/un-miracle.jpg" alt="Un miracle avec 1 dollar - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/le-livre-des-disputes.php" title="Le livre des disputes - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/livre-disputes.jpg" alt="Le livre des disputes - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/jesus-et-les-trois-pains.php" title="Jésus et les 3 pains - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/jesus-pain.jpg" alt="Jésus et les 3 pains - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/apaise-ton-coeur.php" title="Apaise ton cœur - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/apaise-ton-coeur.jpg" alt="Apaise ton cœur - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/epouser-ou-pas.php" title="L'épouser ou pas ? - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/epouser.jpg" alt="L'épouser ou pas ? - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/eleve-nul-en-physique.php" title="L'élève nul en physique - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/nul-physique.jpg" alt="L'élève nul en physique - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/une-histoire-qui-depasse-imagination.php" title="Une histoire qui dépasse l'imagination - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/depasse-imagination.jpg" alt="Une histoire qui dépasse l'imagination - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/le-choix-de-mourinho.php" title="Le choix de Mourinho - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/mourihno.jpg" alt="Le choix de Mourinho - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/jesus-maman.php" title="Jésus et la maman triste - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/jesus.jpg" alt="Jésus et la maman triste - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/bonne-fete-des-meres.php" title="Bonne fête des mères - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/fete_mere.jpg" alt="Bonne fête des mères - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/ecole-de-la-vie.php" title="L'école de la vie - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/ecole.jpg" alt="L'école de la vie - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/la-statue-or.php" title="La statue d'or - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/statue_or.jpg" alt="La statue d'or - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/qui-est-ta-maman.php" title="Qui est ta maman ? - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/maman.jpg" alt="Qui est ta maman ? - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/eau-a-medine.php" title="L'eau à Médine - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/eau.jpg" alt="L'eau à Médine - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/a-la-recherche-un-travail.php" title="À la recherche d'un travail - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/emploi.jpg" alt="À la recherche d'un travail - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/une-ecurie-de-chevaux.php" title="Une écurie de chevaux - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/ecurie.jpg" alt="Une écurie de chevaux - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/anniversaire-de-ma-femme.php" title="L'anniversaire de ma femme - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/anniversaire.jpg" alt="L'anniversaire de ma femme - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/la-tribu-des-ashantis.php" title="La tribu des Ashantis - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/tribu.jpg" alt="La tribu des Ashantis - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/moise-et-le-jeune-qui-voulait-devenir-riche.php" title="Moïse et le jeune qui voulait devenir riche - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/moise.jpg" alt="Moïse et le jeune qui voulait devenir riche - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/la-tricherie-en-coree-du-sud.php" title="La tricherie en Corée du sud - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/triche.jpg" alt="La tricherie en Corée du sud - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/une-femme-talentueuse.php" title="Une femme talentueuse - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/femme.jpg" alt="Une femme talentueuse - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/toujours-pas-mariee.php" title="34 ans et toujours pas mariée - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/mariee.jpg" alt="34 ans et toujours pas mariée - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/la-chaussure-de-gandhi.php" title="La chaussure de Gandhi - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/gandhi.jpg" alt="La chaussure de Gandhi - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/histoire-fille-pauvre-tres-riche.php" title="L'histoire d'une fille pauvre très riche - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/pauvre.jpg" alt="L'histoire d'une fille pauvre très riche - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/orphelin-et-le-palmier.php" title="L'orphelin et le palmier - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/palmier.jpg" alt="L'orphelin et le palmier - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/echouer-dans-la-vie.php" title="Échouer dans la vie - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/echouer.jpg" alt="Échouer dans la vie - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/la-promesse-un-papa.php" title="La promesse d'un papa - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/promesse_papa.jpg" alt="La promesse d'un papa - Un sourire d'espoir 3" /></a></figure><figure><a href="../un-sourire-espoir3/une-journee-a-hopital.php" title="Une journée à l'hôpital - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/journee_hopital.jpg" alt="Une journée à l'hôpital - Un sourire d'espoir 3" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/histoire-de-taj-mahal.php" title="L'histoire de Taj Mahal - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/tajmahal.jpg" alt="L'histoire de Taj Mahal - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/un-enfant-chez-le-dentiste.php" title="Un enfant chez le dentiste - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/enfant_dentiste.jpg" alt="Un enfant chez le dentiste - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/la-circulation-en-inde.php" title="La circulation en Inde - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/circulation_inde.jpg" alt="La circulation en Inde - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/une-maman-abandonnee.php" title="Une maman abandonnée - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/maman_abandonnee.jpg" alt="Une maman abandonnée - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/une-maison-face-a-la-mer.php" title="Une maison face à la mer - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/maison_mer.jpg" alt="Une maison face à la mer - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/lettre-d-un-mari.php" title="Lettre d'un mari - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/lettre_mari.jpg" alt="Lettre d'un mari - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/les-voleurs-et-la-robe-de-mariee.php" title="Les voleurs et la robe de mariée - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/voleur_robe.jpg" alt="Les voleurs et la robe de mariée - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/comment-etre-optimiste.php" title="Comment être optimiste - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/rester_optimiste.jpg" alt="Comment être optimiste - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/le-voleur-de-pain.php" title="Le voleur de pain - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/voleur_pain.jpg" alt="Le voleur de pain - Un sourire d'espoir 3  Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/lettre-a-mon-papa.php" title="Lettre à mon Papa - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/lettre_a_mon_papa.jpg" alt="Lettre à mon Papa - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/experience-louis-xiv.php" title="L'expérience de Louis XIV - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/louis14.jpg" alt="L'expérience de Louis XIV - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/les-cigarettes-de-la-mort.php" title="Les cigarettes de la mort - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/cigarette.jpg" alt="Les cigarettes de la mort - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/histoire-marin-et-architecte.php" title="L'histoire du marin et l'architecte - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/marin_architecte.jpg" alt="L'histoire du marin et l'architecte - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/un-francais-converti-a-islam.php" title="L'histoire d'un français converti à l'islam - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/francais_converti.jpg" alt="L'histoire d'un français converti à l'islam - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/histoire-maman-japonaise.php" title="L'histoire d'une maman japonaise - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/mama_japonaise.jpg" alt="L'histoire d'une maman japonaise"/></a></figure><figure><a href="../un-sourire-espoir3/dans-la-tete-d-un-muscle.php" title="Dans la tête d'un musclé - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/muscle.jpg" alt="Dans la tête d'un musclé - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/ne-laisse-pas-les-autres-te-decourager.php" title="Ne laisse pas les autres te décourager - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/decourager.jpg" alt="Ne laisse pas les autres te décourager - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/le-secret-mariage.php" title="Le secret d'un mariage qui a duré 55 ans - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/mariage.jpg" alt="Le secret d'un mariage qui a duré 55 ans - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/etre-jeune-et-reussir.php" title="Être jeune et réussir - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/jeunereussir.jpg" alt="Être jeune et réussir - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/un-bocal-de-cornichons.php" title="Un bocal de cornichons - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/cornichon.jpg" alt="Un bocal de cornichons - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/orphelin-et-coeur-noir.php" title="L'orphelin et le cœur noir - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/orphelin.jpg" alt="L'orphelin et le cœur noir - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/comment-reussir-sans-limite.php" title="Comment réussir sans limite - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/reussir_sans_limite.jpg" alt="Comment réussir sans limite - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/mauvaise-journee.php" title="Tu as passé une mauvaise journée? - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/mauvaise_journee.jpg" alt="Tu as passé une mauvaise journée? - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/une-famille-elephants.php" title="Une famille d'éléphants - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/elephants.jpg" alt="Une famille d'éléphants - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/jeunes-positifs.php" title="Des jeunes positifs... - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/jeunes_positifs.jpg" alt="Des jeunes positifs... - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/une-rencontre-dans-le-metro.php" title="Une rencontre dans le métro - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/metro.jpg" alt="Une rencontre dans le métro - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/architecte.php" title="L'histoire d'un architecte - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/architecte.jpg" alt="L'histoire d'un architecte - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/changer-metier.php" title="Changer de métier - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/changer_metier.jpg" alt="Changer de métier - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/vallee-des-aveugles.php" title="L'histoire de la vallée des aveugles - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/aveugle.jpg" alt="L'histoire de la vallée des aveugles - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/une-dispute-au-tribunal.php" title="Une dispute au tribunal - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/tribunal.jpg" alt="Une dispute au tribunal - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/naissance-prophete-mohammed.php" title="La naissance du Prophète Mohamed - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/naissance_prophete.jpg" alt="La naissance du Prophète Mohamed - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/transformer-souffrance-en-bonheur.php" title="Comment transformer ta souffrance en bonheur - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/souffrance.jpg" alt="Comment transformer ta souffrance en bonheur - Un sourire d'espoir 3 Amr Khaled" /></a></figure>
                                <figure><a href="../un-sourire-espoir3/experience-vase-pierre.php" title="Une expérience avec un vase et des pierres - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/experience-vase-pierre.jpg" alt="Une expérience avec un vase et des pierres - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/un-verre-de-lait.php" title="Améliore le monde avec un verre de lait - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/lait.jpg" alt="Améliore le monde avec un verre de lait - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/couvertures-hiver.php" title="Des couvertures d'hiver - Un sourire d'espoir 3"><img src="../img/img-saison/saison3/couverture.jpg" alt="Des couvertures d'hiver - Un sourire d'espoir 3 Amr Khaled" /></a></figure><figure><a href="../un-sourire-espoir3/intro-saison3.php" title="Un sourire d'espoir saison 3 : Annonce"><img src="../img/img-saison/saison3/saison3se.jpg" alt="Un sourire d'espoir saison 3 : Annonce" /></a></figure>
                        </div>
                        <footer class="footer-episode-saison">
                            <div class="pagination"><p class="lien-active" title="Un Sourire d'espoir saison 3 - Page 1">1</p><a href="saison3-part2.php" title="Un Sourire d'espoir saison 2 - Page 2">2</a></div>
                        </footer>
                    </section>
                            <?php
                            include("../pub.php");
                        ?>
                </div>
                </div>
        </body>
    </html>